version: 2
updates:
- package-ecosystem: pip
  directory: "/base"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pymssql
    versions:
    - "> 2.1.4"
