image: ghcr.io/home-assistant/{arch}-homeassistant-base
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18
  armhf: ghcr.io/home-assistant/armhf-base-python:3.11-alpine3.18
  armv7: ghcr.io/home-assistant/armv7-base-python:3.11-alpine3.18
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18
  i386: ghcr.io/home-assistant/i386-base-python:3.11-alpine3.18
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
cosign:
  base_identity: https://github.com/home-assistant/docker-base/.*
  identity: https://github.com/home-assistant/docker/.*
labels:
  io.hass.type: homeassistant-base
  org.opencontainers.image.title: Home Assistant Core baseimage
  org.opencontainers.image.description: Baseimage for Home Assistant Core container/supervisor installation
  org.opencontainers.image.source: https://github.com/home-assistant/docker
  org.opencontainers.image.authors: The Home Assistant Authors
  org.opencontainers.image.url: https://www.home-assistant.io/
  org.opencontainers.image.documentation: https://www.home-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
args:
  SSOCR_VERSION: 2.22.1
  LIBCEC_VERSION: 6.0.2
  TELLDUS_COMMIT: 2598bbed16ffd701f2a07c99582f057a3decbaf3
  PICOTTS_HASH: e3ba46009ee868911fa0b53db672a55f9cc13b1c
