name: 'Shellcheck'

on:
  push:
    branch:
      - master
  pull_request:  

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
      env:
        SHELLCHECK_OPTS: -s bash